openapi: 3.0.0
info:
  title: Marketing Campaign API
  description: API for managing SMS marketing campaigns
  version: 1.0.0
servers:
  - url: https://api.example.com/dev
    description: Development server
  - url: http://localhost:3000
    description: Local development
paths:
  /campaigns:
    post:
      summary: Create a new campaign
      description: Create a new SMS marketing campaign
      tags:
        - Campaigns
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - message
                - phoneNumbers
                - scheduledDate
              properties:
                name:
                  type: string
                  description: Name of the campaign
                message:
                  type: string
                  description: Message to be sent to recipients
                phoneNumbers:
                  type: array
                  items:
                    type: string
                  description: List of phone numbers to send the message to
                scheduledDate:
                  type: string
                  format: date-time
                  description: Date and time to schedule the campaign
      responses:
        '201':
          description: Campaign created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  message:
                    type: string
                  scheduledDate:
                    type: string
                    format: date-time
                  processStatus:
                    type: integer
                    enum: [1, 2, 3]
                    description: '1: pending, 2: in process, 3: finished'
        '400':
          description: Invalid input
        '500':
          description: Server error
    get:
      summary: List campaigns
      description: Get a list of campaigns with optional date filtering
      tags:
        - Campaigns
      parameters:
        - name: startDate
          in: query
          description: Start date to filter campaigns
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: End date to filter campaigns
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of campaigns
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    message:
                      type: string
                    scheduledDate:
                      type: string
                      format: date-time
                    processStatus:
                      type: integer
                      enum: [1, 2, 3]
                      description: '1: pending, 2: in process, 3: finished'
                    totalMessages:
                      type: integer
                    sentMessages:
                      type: integer
                    errorMessages:
                      type: integer
  /campaigns/{id}:
    get:
      summary: Get campaign details
      description: Get details of a specific campaign
      tags:
        - Campaigns
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Campaign ID
      responses:
        '200':
          description: Campaign details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  message:
                    type: string
                  scheduledDate:
                    type: string
                    format: date-time
                  processStatus:
                    type: integer
                    enum: [1, 2, 3]
                    description: '1: pending, 2: in process, 3: finished'
                  totalMessages:
                    type: integer
                  sentMessages:
                    type: integer
                  errorMessages:
                    type: integer
        '404':
          description: Campaign not found
  /campaigns/{id}/process:
    post:
      summary: Process a campaign
      description: Start processing a campaign, sending messages to recipients
      tags:
        - Campaigns
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Campaign ID
      responses:
        '200':
          description: Campaign processing started
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  processStatus:
                    type: integer
                    enum: [2]
                    description: '2: in process'
        '400':
          description: Campaign already processed
        '404':
          description: Campaign not found
  /campaigns/{id}/messages:
    get:
      summary: List campaign messages
      description: Get a list of messages for a specific campaign
      tags:
        - Messages
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Campaign ID
        - name: status
          in: query
          schema:
            type: integer
            enum: [1, 2, 3]
          description: "Filter by shipping status 1: pending 2: sent 3: error"
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    campaignId:
                      type: integer
                    phoneNumber:
                      type: string
                    shippingStatus:
                      type: integer
                      enum: [1, 2, 3]
                      description: '1: pending, 2: sent, 3: error'
                    sentAt:
                      type: string
                      format: date-time
                    errorMessage:
                      type: string
        '404':
          description: Campaign not found
components:
  schemas:
    Campaign:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        message:
          type: string
        scheduledDate:
          type: string
          format: date-time
        processStatus:
          type: integer
          enum: [1, 2, 3]
          description: '1: pending, 2: in process, 3: finished'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Message:
      type: object
      properties:
        id:
          type: integer
        campaignId:
          type: integer
        phoneNumber:
          type: string
        shippingStatus:
          type: integer
          enum: [1, 2, 3]
          description: '1: pending, 2: sent, 3: error'
        sentAt:
          type: string
          format: date-time
        errorMessage:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time