# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alexmartinez

app: sendmessages

service: sinapsis

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  environment:
    SERVERLESS_ACCESS_KEY: ${env:SERVERLESS_ACCESS_KEY}

plugins:
  - serverless-offline
  - serverless-openapi-documentation

custom:
  documentation:
    api:
      info:
        title: Marketing Campaign API
        description: API for managing SMS marketing campaigns
        version: 1.0.0
      servers:
        - url: https://api.example.com/dev
          description: Development server
        - url: http://localhost:3000
          description: Local development

functions:
  api:
    handler: src/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
